language: python
python:
  - "3.6"

install:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then pip install dawg; fi
  - pip install coverage pytest-cov coveralls
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - py.test --cov=circuit_dawg

after_success:
  - coveralls
